
# TODO: change to mysql
datasources:
  default:
    url: jdbc:h2:mem:sgg;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    schema-generate: CREATE_DROP

jpa:
  default:
    properties:
      hibernate:
        show_sql: true
