micronaut:
  application:
    name: seasongg-services
  server:
    port: 3000
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET}"
        generator:
          refresh-token:
            secret: "${JWT_GENERATOR_REFRESH_SECRET}"

datasources:
  default:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
