apiVersion: /v1

micronaut:
  application:
    name: seasongg-services
  server:
    port: 3000
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET}"
        generator:
          refresh-token:
            secret: "${JWT_GENERATOR_REFRESH_SECRET}"

jackson:
  serialization:
    writeDatesAsTimestamps: false
