micronaut:
  security:
    endpoints:
      oauth:
        enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "localSignatureGeneratorSecretKey"
        generator:
          refresh-token:
            secret: "localRefreshTokenGeneratorSecret"

# TODO: replace with MySQL info and use testcontainers
datasources:
  default:
    url: jdbc:h2:mem:sgg;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    schema-generate: CREATE_DROP

jpa:
  default:
    properties:
      hibernate:
        show_sql: true


logger:
  levels:
    io.micronaut: INFO