micronaut:
  security:
    endpoints:
      oauth:
        enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "localSignatureGeneratorSecretKey"
        generator:
          refresh-token:
            secret: "localRefreshTokenGeneratorSecret"

datasources:
  default:
    url: jdbc:mysql://localhost:3306/sgg?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

jpa:
  default:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: create
        show_sql: true

logger:
  levels:
    io.micronaut: INFO
